import omegaConstellationImg from "@assets/generated_images/omega_constellation_half_gold_watch.png";
import omegaSeamasterImg from "@assets/generated_images/omega_seamaster_black_dial_watch.png";
import iranianCarpetImg from "@assets/generated_images/1910_iranian_handmade_carpet.png";
import seikoPandaImg from "@assets/generated_images/seiko_panda_1973_vintage_watch.png";
import longinesImg from "@assets/generated_images/longines_vintage_handwatch.png";
import casioImg from "@assets/generated_images/casio_vintage_digital_watch.png";

import carpet1Img from "@assets/2cbff6e6-4ce1-40db-8ac6-2e61e91a2395_1766158990916.JPG";
import carpet2Img from "@assets/2e82a6cf-751c-4c08-a9c6-a0f491020f95_1766158990916.JPG";
import carpet3Img from "@assets/7c799269-35e0-47c4-823c-0b01223cecd0_1766158990916.JPG";
import carpet4Img from "@assets/028fe048-57e3-4262-a806-1bc5d0c4c532_1766158990916.JPG";
import carpet5Img from "@assets/41c25904-395a-41a2-ac0d-4af3173b5362_1766158990916.JPG";
import carpet6Img from "@assets/626001e2-8e3a-4c35-921a-53ddcfc796cc_1766158990916.JPG";
import carpet7Img from "@assets/a42dcb7a-49c4-43d4-926c-b2e7a22b67d4_1766158990916.JPG";
import carpet8Img from "@assets/a457b57a-0ba1-4755-ac5f-03f95a099ade_1766158990916.JPG";
import carpet9Img from "@assets/a04207f5-2571-46b4-841c-362ee40648e8_1766158990916.JPG";
import carpet10Img from "@assets/c40cda45-bc0b-4043-82e4-9be9ead0ad94_1766158990916.JPG";
import carpet11Img from "@assets/cca3fe30-32b9-41df-8171-8207b46ff327_1766158990916.JPG";

export interface Seller {
  name: string;
  salesCount: number;
  rating: number;
}

export interface Product {
  id: string;
  productCode: string;
  title: string;
  price: number;
  currentBid?: number;
  totalBids?: number;
  image: string;
  category: string;
  timeLeft?: string;
  auctionEndTime?: string | Date | null;
  saleType?: "auction" | "fixed";
  condition: "New" | "Used - Like New" | "Used - Good" | "Vintage";
  description?: string;
  seller: Seller;
  sellerName?: string;
  sellerTotalSales?: number;
  sellerRating?: number;
  deliveryWindow: string;
  returnPolicy: string;
  returnDetails?: string;
  city?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "1",
    productCode: "P-100001",
    title: "ساعة أوميغا كونستليشن - نصف ذهب باي بان",
    price: 3500000,
    currentBid: 3200000,
    totalBids: 67,
    image: omegaConstellationImg,
    category: "ساعات",
    timeLeft: "6 ساعات",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "ساعة أوميغا كونستليشن الأيقونية من الستينيات. تصميم نصف ذهب وستيل مع قرص باي بان الشهير. الحركة الأوتوماتيكية تعمل بكفاءة تامة. قطعة نادرة لهواة الساعات الكلاسيكية.",
    seller: { name: "ساعات التراث", salesCount: 1250, rating: 99 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "ضمان أصالة مع شهادة",
    city: "بغداد",
  },
  {
    id: "2",
    productCode: "P-100002",
    title: "ساعة أوميغا سيماستر - قرص أسود",
    price: 2800000,
    currentBid: 2500000,
    totalBids: 45,
    image: omegaSeamasterImg,
    category: "ساعات",
    timeLeft: "12 ساعة",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 12 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "ساعة أوميغا سيماستر فينتج مع قرص أسود أنيق. من الستينيات. حالة ممتازة للعمر. الحركة الأوتوماتيكية تعمل بدقة. قطعة كلاسيكية للرجل الأنيق.",
    seller: { name: "متجر الأناقة", salesCount: 890, rating: 98 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "فحص مجاني قبل الشراء",
    city: "بغداد",
  },
  {
    id: "3",
    productCode: "P-100003",
    title: "سجادة إيرانية أصلية 1910 - صناعة يدوية",
    price: 4500000,
    currentBid: 4000000,
    totalBids: 32,
    image: iranianCarpetImg,
    category: "تحف وأثاث",
    timeLeft: "2 يوم",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة إيرانية نادرة من عام 1910. صناعة يدوية 100% من الحرير والصوف الطبيعي. ألوان طبيعية ثابتة. مقاس 3x4 متر. قطعة فنية تاريخية نادرة جداً. شهادة أصالة متوفرة.",
    seller: { name: "حاج كريم الأنتيك", salesCount: 2400, rating: 99 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "ضمان الأصالة التاريخية",
    city: "البصرة",
  },
  {
    id: "4",
    productCode: "P-100004",
    title: "ساعة سيكو باندا فينتج 1973",
    price: 1200000,
    currentBid: 980000,
    totalBids: 28,
    image: seikoPandaImg,
    category: "ساعات",
    timeLeft: "8 ساعات",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "ساعة سيكو كرونوغراف باندا الأيقونية من 1973. القرص الأبيض مع العدادات السوداء. تصميم سباقات السيارات الكلاسيكي. حالة ممتازة. قطعة مطلوبة جداً من هواة الساعات.",
    seller: { name: "ساعات الزمن الجميل", salesCount: 567, rating: 97 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "فحص تقني مع ضمان",
    city: "أربيل",
  },
  {
    id: "5",
    productCode: "P-100005",
    title: "ساعة لونجين كلاسيكية",
    price: 1800000,
    currentBid: 1550000,
    totalBids: 41,
    image: longinesImg,
    category: "ساعات",
    timeLeft: "4 ساعات",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "ساعة لونجين فينتج أنيقة من الخمسينيات. قرص أبيض كلاسيكي مع علبة ذهبية. حركة يدوية سويسرية دقيقة. مثالية للمناسبات الرسمية. قطعة راقية للذواقة.",
    seller: { name: "تجارة الساعات الفاخرة", salesCount: 1100, rating: 98 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "شهادة أصالة سويسرية",
    city: "بغداد",
  },
  {
    id: "6",
    productCode: "P-100006",
    title: "ساعة كاسيو كلاسيكية",
    price: 85000,
    totalBids: 15,
    image: casioImg,
    category: "ساعات",
    saleType: "fixed",
    condition: "Vintage",
    description: "ساعة كاسيو رقمية كلاسيكية من الثمانينيات. التصميم الأيقوني المحبوب. شاشة LCD واضحة. حالة ممتازة للعمر. قطعة ريترو للمحبين.",
    seller: { name: "متجر النوستالجيا", salesCount: 234, rating: 95 },
    deliveryWindow: "1-3 أيام",
    returnPolicy: "3 أيام",
    city: "الموصل",
  },
  {
    id: "7",
    productCode: "P-100007",
    title: "سجادة صلاة إيرانية حريرية - شجرة الحياة والطيور",
    price: 8500000,
    currentBid: 7200000,
    totalBids: 89,
    image: carpet1Img,
    category: "تحف وأثاث",
    timeLeft: "3 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة صلاة إيرانية فاخرة من الحرير الطبيعي. تصميم شجرة الحياة المقدسة مع طيور الجنة. خلفية حمراء غنية مع إطار أسود مزخرف بالورود. صناعة يدوية دقيقة من منطقة قم. حالة ممتازة محفوظة بعناية. قطعة نادرة للمجموعات الفنية الراقية.",
    seller: { name: "غاليري السجاد الفاخر", salesCount: 3200, rating: 99 },
    deliveryWindow: "5-7 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "شهادة أصالة وتقييم من خبراء",
    city: "بغداد",
  },
  {
    id: "8",
    productCode: "P-100008",
    title: "سجادة تبريز كلاسيكية - وردي وأزرق ملكي",
    price: 6200000,
    currentBid: 5400000,
    totalBids: 56,
    image: carpet2Img,
    category: "تحف وأثاث",
    timeLeft: "5 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة تبريز إيرانية أصيلة بتصميم ميدالية مركزية. ألوان وردية وزرقاء ملكية متناسقة. نقوش هندسية وزهرية معقدة. صوف وحرير طبيعي عالي الجودة. مقاس 2.5×3.5 متر. تحفة فنية للصالونات الفخمة.",
    seller: { name: "بيت السجاد العراقي", salesCount: 1890, rating: 98 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "فحص مجاني قبل الاستلام",
    city: "البصرة",
  },
  {
    id: "9",
    productCode: "P-100009",
    title: "سجادة أصفهانية عتيقة - تصميم ميداليون",
    price: 4800000,
    currentBid: 4100000,
    totalBids: 38,
    image: carpet3Img,
    category: "تحف وأثاث",
    timeLeft: "4 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة أصفهانية تاريخية بألوان أرضية دافئة. ميداليون مركزي بيج وبني مع زخارف نباتية. إطار كريمي مزخرف. عمرها يتجاوز 80 عاماً. حالة جيدة تظهر جمال العمر. قطعة تراثية للديكور الكلاسيكي.",
    seller: { name: "كنوز الشرق", salesCount: 2100, rating: 97 },
    deliveryWindow: "5-7 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "تقرير حالة مفصل متوفر",
    city: "النجف",
  },
  {
    id: "10",
    productCode: "P-100010",
    title: "سجادة حديقة كشمير - تصميم المربعات",
    price: 12000000,
    currentBid: 10500000,
    totalBids: 124,
    image: carpet4Img,
    category: "تحف وأثاث",
    timeLeft: "6 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة رانر كشميرية نادرة بتصميم حديقة الجنة. 24 مربعاً منفصلاً كل منها يحتوي رسماً مختلفاً من الأشجار والورود والمزهريات. حرير طبيعي 100%. صناعة يدوية فائقة الدقة. مقاس 1.5×4 متر. تحفة نادرة جداً من القرن التاسع عشر.",
    seller: { name: "معرض التحف النفيسة", salesCount: 4500, rating: 99 },
    deliveryWindow: "7-10 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "شهادة تاريخية وتقييم خبراء دوليين",
    city: "بغداد",
  },
  {
    id: "11",
    productCode: "P-100011",
    title: "سجادة قم حريرية - ورود كلاسيكية",
    price: 7500000,
    currentBid: 6800000,
    totalBids: 67,
    image: carpet5Img,
    category: "تحف وأثاث",
    timeLeft: "2 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة قم إيرانية من الحرير الخالص. تصميم زهري كثيف بألوان الكريم والعنابي والأخضر. ميداليون مركزي محاط بباقات الورود. إطار كحلي مزخرف. جودة استثنائية ونسيج متين. مقاس 2×3 متر. للصالونات الراقية.",
    seller: { name: "سجاد الأصالة", salesCount: 2800, rating: 98 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "ضمان جودة وأصالة",
    city: "كربلاء",
  },
  {
    id: "12",
    productCode: "P-100012",
    title: "سجادة تبريز زهرية - كريم وتراكوتا",
    price: 3200000,
    totalBids: 0,
    image: carpet6Img,
    category: "تحف وأثاث",
    saleType: "fixed",
    condition: "Vintage",
    description: "سجادة تبريز بتصميم زهري بسيط وأنيق. خلفية كريمية فاتحة مع زخارف زهرية بألوان التراكوتا والأخضر الزيتوني. إطار مزدوج. صوف طبيعي عالي الكثافة. مقاس 1.7×2.5 متر. مثالية لغرف الضيوف والمكاتب.",
    seller: { name: "بازار السجاد الشرقي", salesCount: 1200, rating: 96 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "7 أيام",
    city: "أربيل",
  },
  {
    id: "13",
    productCode: "P-100013",
    title: "سجادة نائين فاخرة - ميداليون ذهبي",
    price: 9800000,
    currentBid: 8500000,
    totalBids: 78,
    image: carpet7Img,
    category: "تحف وأثاث",
    timeLeft: "4 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة نائين إيرانية من الدرجة الأولى. ميداليون ذهبي مركزي على خلفية كريمية. زخارف نباتية وزهرية متشابكة بألوان الأزرق والأحمر. إطار رمادي مائل للوردي. حرير وصوف طبيعي. مقاس 2.5×3.5 متر. قطعة متحفية.",
    seller: { name: "غاليري السجاد الفاخر", salesCount: 3200, rating: 99 },
    deliveryWindow: "5-7 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "تقييم خبراء مع شهادة",
    city: "بغداد",
  },
  {
    id: "14",
    productCode: "P-100014",
    title: "سجادة كاشان مركزية - زهرية وردية",
    price: 5500000,
    currentBid: 4800000,
    totalBids: 45,
    image: carpet8Img,
    category: "تحف وأثاث",
    timeLeft: "5 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة كاشان إيرانية بتصميم مميز. مركز داكن محاط بخلفية وردية سلمون. زخارف زهرية كثيفة بألوان متعددة. إطار كحلي غني. صوف وحرير مخلوط. مقاس 2×3 متر. طابع كلاسيكي فريد.",
    seller: { name: "كنوز الشرق", salesCount: 2100, rating: 97 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "فحص مع خبير قبل الشراء",
    city: "السليمانية",
  },
  {
    id: "15",
    productCode: "P-100015",
    title: "سجادة هريز أذربيجانية - نجمة مركزية",
    price: 4200000,
    totalBids: 0,
    image: carpet9Img,
    category: "تحف وأثاث",
    saleType: "fixed",
    condition: "Vintage",
    description: "سجادة هريز أذربيجانية بتصميم هندسي قوي. ميداليون نجمي كبير على خلفية تراكوتا. ركنيات مزخرفة بألوان الكريم والأزرق. إطار متعدد الطبقات. صوف جبلي متين. مقاس 2.2×3.2 متر. مثالية للمساحات الكبيرة.",
    seller: { name: "بيت السجاد العراقي", salesCount: 1890, rating: 98 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "14 يوم",
    city: "الموصل",
  },
  {
    id: "16",
    productCode: "P-100016",
    title: "سجادة بيجار كردية - ميداليون تقليدي",
    price: 6800000,
    currentBid: 5900000,
    totalBids: 52,
    image: carpet10Img,
    category: "تحف وأثاث",
    timeLeft: "3 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة بيجار كردية أصيلة بتصميم ميداليون كلاسيكي. خلفية حمراء عميقة مع ميداليون كحلي مركزي. زخارف تقليدية دقيقة. إطار كريمي وكحلي. صوف كردي كثيف ومتين. مقاس 1.5×2.2 متر. قطعة تراثية أصيلة.",
    seller: { name: "سجاد كردستان", salesCount: 980, rating: 97 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "شهادة منشأ كردي",
    city: "أربيل",
  },
  {
    id: "17",
    productCode: "P-100017",
    title: "سجادة نائين ملكية - أزرق كحلي فاخر",
    price: 11000000,
    currentBid: 9500000,
    totalBids: 95,
    image: carpet11Img,
    category: "تحف وأثاث",
    timeLeft: "7 أيام",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة نائين ملكية من أجود أنواع الحرير الإيراني. خلفية كحلية عميقة مع ميداليون مركزي بيج وذهبي. زخارف نباتية متشابكة بدقة استثنائية. إطار كريمي فاخر. مقاس 2×3 متر. قطعة متحفية نادرة من مجموعة خاصة.",
    seller: { name: "معرض التحف النفيسة", salesCount: 4500, rating: 99 },
    deliveryWindow: "7-10 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "تقييم دولي مع شهادة أصالة",
    city: "بغداد",
  },
];
