
import watchImg from "@assets/generated_images/vintage_gold_watch.png";
import jacketImg from "@assets/generated_images/vintage_leather_jacket.png";

export interface Seller {
  name: string;
  salesCount: number;
  rating: number;
}

export interface Product {
  id: string;
  title: string;
  price: number;
  currentBid?: number;
  totalBids?: number;
  image: string;
  category: string;
  timeLeft?: string;
  auctionEndTime?: string | Date | null;
  saleType?: "auction" | "fixed";
  condition: "New" | "Used - Like New" | "Used - Good" | "Vintage";
  description?: string;
  seller: Seller;
  sellerName?: string;
  sellerTotalSales?: number;
  sellerRating?: number;
  deliveryWindow: string;
  returnPolicy: string;
  returnDetails?: string;
  city?: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "1",
    title: "آيفون 14 برو ماكس 256GB - لون ذهبي",
    price: 1450000,
    currentBid: 1320000,
    totalBids: 47,
    image: "https://images.unsplash.com/photo-1678685888221-cda773a3dcdb?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    timeLeft: "4 ساعات",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 4 * 60 * 60 * 1000).toISOString(),
    condition: "Used - Like New",
    description: "آيفون 14 برو ماكس بحالة ممتازة جداً. البطارية 96%. الشاشة والكاميرا بدون أي خدوش. يأتي مع الشاحن الأصلي والعلبة. تم شراؤه من أمريكا. مفتوح لجميع الشبكات.",
    seller: { name: "علي التقني", salesCount: 890, rating: 97 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "ضمان الفحص الكامل قبل الشراء",
  },
  {
    id: "2",
    title: "سجادة إيرانية حرير أصلية - قطعة نادرة",
    price: 2500000,
    currentBid: 2100000,
    totalBids: 23,
    image: "https://images.unsplash.com/photo-1600166898405-da9535204843?w=400&h=400&fit=crop",
    category: "تحف وأثاث",
    timeLeft: "2 يوم",
    saleType: "auction",
    auctionEndTime: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(),
    condition: "Vintage",
    description: "سجادة إيرانية أصلية من الحرير الطبيعي 100%. عمرها أكثر من 80 سنة. مقاس 3x4 متر. ألوان طبيعية ثابتة. قطعة فنية نادرة جداً من أصفهان. شهادة أصالة متوفرة.",
    seller: { name: "حاج كريم الأنتيك", salesCount: 2400, rating: 99 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "ضمان الأصالة مع إرجاع كامل",
  },
  {
    id: "3",
    title: "ساعة رولكس ديت جست - ستيل وذهب",
    price: 4200000,
    currentBid: 3800000,
    totalBids: 89,
    image: watchImg,
    category: "ساعات",
    timeLeft: "6 ساعات",
    condition: "Vintage",
    description: "ساعة رولكس ديت جست الأيقونية. موديل 1985. ستيل وذهب أصلي. القرص الشمباني الكلاسيكي. الحركة تعمل بكفاءة 100%. شهادة من وكيل رولكس. قطعة استثمارية.",
    seller: { name: "حسين النجفي", salesCount: 3200, rating: 100 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "30 يوم",
    returnDetails: "ضمان أصالة مع فحص مجاني",
  },
  {
    id: "4",
    title: "بلايستيشن 5 مع ذراعين - إصدار الأقراص",
    price: 750000,
    totalBids: 31,
    image: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    condition: "Used - Like New",
    description: "بلايستيشن 5 إصدار الأقراص بحالة ممتازة. يأتي مع ذراعين أصليين وجميع الكوابل. تم استخدامه لمدة 6 أشهر فقط. لا يوجد أي مشاكل تقنية.",
    seller: { name: "أحمد الجيمر", salesCount: 156, rating: 94 },
    deliveryWindow: "1-3 أيام",
    returnPolicy: "3 أيام",
    returnDetails: "فحص كامل قبل الاستلام",
  },
  {
    id: "5",
    title: "طقم ذهب عراقي 21 قيراط - للعروس",
    price: 3800000,
    currentBid: 3500000,
    totalBids: 56,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop",
    category: "أخرى",
    timeLeft: "1 يوم",
    condition: "New",
    description: "طقم ذهب عراقي أصلي 21 قيراط. يشمل عقد، أساور، خواتم، وحلق. وزن إجمالي 85 غرام. تصميم عراقي تقليدي فاخر. مثالي للأعراس. مع فاتورة الصياغة.",
    seller: { name: "صياغة الزهراء", salesCount: 1800, rating: 98 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "ضمان الذهب والوزن",
  },
  {
    id: "6",
    title: "جاكيت جلد إيطالي أصلي - مقاس XL",
    price: 180000,
    totalBids: 12,
    image: jacketImg,
    category: "ملابس",
    condition: "Used - Good",
    description: "جاكيت جلد طبيعي من ماركة إيطالية فاخرة. مقاس XL. اللون بني غامق. بحالة جيدة مع علامات استخدام بسيطة تضيف للطابع الكلاسيكي.",
    seller: { name: "فاطمة الموصلية", salesCount: 85, rating: 92 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "3 أيام",
  },
  {
    id: "7",
    title: "لابتوب ماك بوك برو M2 - 14 إنش",
    price: 2200000,
    currentBid: 1950000,
    totalBids: 34,
    image: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    timeLeft: "12 ساعة",
    condition: "Used - Like New",
    description: "ماك بوك برو 14 إنش مع شريحة M2 Pro. رام 16GB وتخزين 512GB. البطارية 94%. لا خدوش على الشاشة أو الجسم. يأتي مع الشاحن الأصلي.",
    seller: { name: "محمد التقني", salesCount: 445, rating: 96 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "فحص تقني كامل مع ضمان",
  },
  {
    id: "8",
    title: "عود هندي قديم - صناعة يدوية",
    price: 650000,
    totalBids: 18,
    image: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=400&h=400&fit=crop",
    category: "أخرى",
    condition: "Vintage",
    description: "عود هندي أصلي عمره 40 سنة. صناعة يدوية من خشب الجوز والورد. الصوت عميق ودافئ. تم صيانته بالكامل. مثالي للعازفين المحترفين.",
    seller: { name: "أستاذ كاظم الموسيقار", salesCount: 67, rating: 100 },
    deliveryWindow: "5-7 أيام",
    returnPolicy: "لا يوجد إرجاع",
  },
  {
    id: "9",
    title: "كاميرا كانون EOS R5 مع عدسة 24-70mm",
    price: 3500000,
    currentBid: 3100000,
    totalBids: 29,
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    timeLeft: "18 ساعة",
    condition: "Used - Like New",
    description: "كاميرا كانون EOS R5 الاحترافية. تصوير 8K فيديو و45 ميجابكسل صور. تأتي مع عدسة RF 24-70mm f/2.8L. عدد الشاتر 12,000 فقط. حالة ممتازة.",
    seller: { name: "ستوديو النور", salesCount: 234, rating: 97 },
    deliveryWindow: "1-3 أيام",
    returnPolicy: "7 أيام",
    returnDetails: "فحص تقني مع ضمان الشاتر",
  },
  {
    id: "10",
    title: "طاولة سفرة خشب زان - 8 كراسي",
    price: 1200000,
    totalBids: 9,
    image: "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400&h=400&fit=crop",
    category: "تحف وأثاث",
    condition: "Used - Good",
    description: "طاولة سفرة فاخرة من خشب الزان الطبيعي. تأتي مع 8 كراسي متطابقة. التصميم كلاسيكي عراقي. بحالة جيدة جداً. قابلة للتمديد.",
    seller: { name: "نجارة الأمين", salesCount: 320, rating: 95 },
    deliveryWindow: "5-7 أيام",
    returnPolicy: "3 أيام",
  },
  {
    id: "11",
    title: "ساعة أوميغا سيماستر - أكوا تيرا",
    price: 1800000,
    currentBid: 1600000,
    totalBids: 42,
    image: watchImg,
    category: "ساعات",
    timeLeft: "8 ساعات",
    condition: "Used - Like New",
    description: "ساعة أوميغا سيماستر أكوا تيرا 41mm. القرص الأزرق الشهير مع حزام ستيل. حركة كوأكسيال الدقيقة. الساعة بحالة ممتازة مع جميع الأوراق والعلبة.",
    seller: { name: "ساعات الخليج", salesCount: 567, rating: 98 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "14 يوم",
  },
  {
    id: "12",
    title: "دراجة هوائية ترينكس - كاربون فريم",
    price: 450000,
    totalBids: 15,
    image: "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&h=400&fit=crop",
    category: "أخرى",
    condition: "Used - Good",
    description: "دراجة هوائية ترينكس بإطار كاربون خفيف. غيارات شيمانو 21 سرعة. فرامل ديسك هيدروليك. مثالية للطرق والمسافات الطويلة. تم استخدامها لموسم واحد.",
    seller: { name: "نادي الدراجات", salesCount: 89, rating: 93 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "3 أيام",
  },
  {
    id: "13",
    title: "تلفزيون سامسونج QLED 65 بوصة - 4K",
    price: 980000,
    currentBid: 850000,
    totalBids: 26,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    timeLeft: "1 يوم",
    condition: "Used - Like New",
    description: "تلفزيون سامسونج QLED 65 بوصة موديل 2023. دقة 4K مع HDR. سمارت تي في مع جميع التطبيقات. الشاشة نظيفة 100%. يأتي مع القاعدة الأصلية والريموت.",
    seller: { name: "إلكترونيات الرافدين", salesCount: 1200, rating: 96 },
    deliveryWindow: "1-3 أيام",
    returnPolicy: "7 أيام",
  },
  {
    id: "14",
    title: "مجموعة عملات عثمانية نادرة",
    price: 750000,
    currentBid: 680000,
    totalBids: 37,
    image: "https://images.unsplash.com/photo-1621155346337-1d19476ba7d6?w=400&h=400&fit=crop",
    category: "تحف وأثاث",
    timeLeft: "3 ساعات",
    condition: "Vintage",
    description: "مجموعة من 25 عملة عثمانية نادرة. تتضمن عملات ذهبية وفضية من القرن 19. حالة ممتازة للمجموعة. شهادة خبير الآثار متوفرة. قطعة للهواة والمستثمرين.",
    seller: { name: "متحف العملات", salesCount: 456, rating: 99 },
    deliveryWindow: "3-5 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "ضمان الأصالة التاريخية",
  },
  {
    id: "15",
    title: "جهاز تكييف سبليت LG 2 طن - انفيرتر",
    price: 520000,
    totalBids: 8,
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    condition: "Used - Good",
    description: "مكيف سبليت LG انفيرتر 2 طن. موفر للطاقة. تم استخدامه موسمين فقط. يعمل بكفاءة عالية. التركيب متوفر. ضمان الكمبروسر سنة.",
    seller: { name: "التبريد الحديث", salesCount: 678, rating: 94 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "3 أيام",
  },
  {
    id: "16",
    title: "سماعات آبل AirPods Pro 2 - جديدة",
    price: 280000,
    totalBids: 19,
    image: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&h=400&fit=crop",
    category: "إلكترونيات",
    condition: "New",
    description: "سماعات آبل AirPods Pro الجيل الثاني. جديدة بالكرتون المغلف. إلغاء الضوضاء النشط. شريحة H2 الجديدة. ضمان آبل سنة كاملة.",
    seller: { name: "تك زون", salesCount: 2300, rating: 97 },
    deliveryWindow: "1-2 أيام",
    returnPolicy: "14 يوم",
    returnDetails: "إرجاع كامل للمنتجات المغلفة",
  },
];
